// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"models"
)

// GetAssignmentsReader is a Reader for the GetAssignments structure.
type GetAssignmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssignmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssignmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAssignmentsOK creates a GetAssignmentsOK with default headers values
func NewGetAssignmentsOK() *GetAssignmentsOK {
	return &GetAssignmentsOK{}
}

/*GetAssignmentsOK handles this case with default header values.

An array for assignment metas
*/
type GetAssignmentsOK struct {
	Payload []*models.Meta
}

func (o *GetAssignmentsOK) Error() string {
	return fmt.Sprintf("[GET /assignments][%d] getAssignmentsOK  %+v", 200, o.Payload)
}

func (o *GetAssignmentsOK) GetPayload() []*models.Meta {
	return o.Payload
}

func (o *GetAssignmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
