// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAssignmentsParams creates a new GetAssignmentsParams object
// with the default values initialized.
func NewGetAssignmentsParams() *GetAssignmentsParams {

	return &GetAssignmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssignmentsParamsWithTimeout creates a new GetAssignmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAssignmentsParamsWithTimeout(timeout time.Duration) *GetAssignmentsParams {

	return &GetAssignmentsParams{

		timeout: timeout,
	}
}

// NewGetAssignmentsParamsWithContext creates a new GetAssignmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAssignmentsParamsWithContext(ctx context.Context) *GetAssignmentsParams {

	return &GetAssignmentsParams{

		Context: ctx,
	}
}

// NewGetAssignmentsParamsWithHTTPClient creates a new GetAssignmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAssignmentsParamsWithHTTPClient(client *http.Client) *GetAssignmentsParams {

	return &GetAssignmentsParams{
		HTTPClient: client,
	}
}

/*GetAssignmentsParams contains all the parameters to send to the API endpoint
for the get assignments operation typically these are written to a http.Request
*/
type GetAssignmentsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get assignments params
func (o *GetAssignmentsParams) WithTimeout(timeout time.Duration) *GetAssignmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assignments params
func (o *GetAssignmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assignments params
func (o *GetAssignmentsParams) WithContext(ctx context.Context) *GetAssignmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assignments params
func (o *GetAssignmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assignments params
func (o *GetAssignmentsParams) WithHTTPClient(client *http.Client) *GetAssignmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assignments params
func (o *GetAssignmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssignmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
