// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAssignmentParams creates a new GetAssignmentParams object
// with the default values initialized.
func NewGetAssignmentParams() *GetAssignmentParams {
	var ()
	return &GetAssignmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssignmentParamsWithTimeout creates a new GetAssignmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAssignmentParamsWithTimeout(timeout time.Duration) *GetAssignmentParams {
	var ()
	return &GetAssignmentParams{

		timeout: timeout,
	}
}

// NewGetAssignmentParamsWithContext creates a new GetAssignmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAssignmentParamsWithContext(ctx context.Context) *GetAssignmentParams {
	var ()
	return &GetAssignmentParams{

		Context: ctx,
	}
}

// NewGetAssignmentParamsWithHTTPClient creates a new GetAssignmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAssignmentParamsWithHTTPClient(client *http.Client) *GetAssignmentParams {
	var ()
	return &GetAssignmentParams{
		HTTPClient: client,
	}
}

/*GetAssignmentParams contains all the parameters to send to the API endpoint
for the get assignment operation typically these are written to a http.Request
*/
type GetAssignmentParams struct {

	/*ID
	  The assignment's id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get assignment params
func (o *GetAssignmentParams) WithTimeout(timeout time.Duration) *GetAssignmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assignment params
func (o *GetAssignmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assignment params
func (o *GetAssignmentParams) WithContext(ctx context.Context) *GetAssignmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assignment params
func (o *GetAssignmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assignment params
func (o *GetAssignmentParams) WithHTTPClient(client *http.Client) *GetAssignmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assignment params
func (o *GetAssignmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get assignment params
func (o *GetAssignmentParams) WithID(id string) *GetAssignmentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get assignment params
func (o *GetAssignmentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssignmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
