// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"rpa-sdk/models"
)

// ReportAssignmentLogReader is a Reader for the ReportAssignmentLog structure.
type ReportAssignmentLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReportAssignmentLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReportAssignmentLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReportAssignmentLogOK creates a ReportAssignmentLogOK with default headers values
func NewReportAssignmentLogOK() *ReportAssignmentLogOK {
	return &ReportAssignmentLogOK{}
}

/*ReportAssignmentLogOK handles this case with default header values.

The data for assignment logs
*/
type ReportAssignmentLogOK struct {
	Payload models.BodyStr
}

func (o *ReportAssignmentLogOK) Error() string {
	return fmt.Sprintf("[POST /assignments/{Id}/log][%d] reportAssignmentLogOK  %+v", 200, o.Payload)
}

func (o *ReportAssignmentLogOK) GetPayload() models.BodyStr {
	return o.Payload
}

func (o *ReportAssignmentLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
