// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReportAssignmentLogParams creates a new ReportAssignmentLogParams object
// with the default values initialized.
func NewReportAssignmentLogParams() *ReportAssignmentLogParams {
	var ()
	return &ReportAssignmentLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReportAssignmentLogParamsWithTimeout creates a new ReportAssignmentLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReportAssignmentLogParamsWithTimeout(timeout time.Duration) *ReportAssignmentLogParams {
	var ()
	return &ReportAssignmentLogParams{

		timeout: timeout,
	}
}

// NewReportAssignmentLogParamsWithContext creates a new ReportAssignmentLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewReportAssignmentLogParamsWithContext(ctx context.Context) *ReportAssignmentLogParams {
	var ()
	return &ReportAssignmentLogParams{

		Context: ctx,
	}
}

// NewReportAssignmentLogParamsWithHTTPClient creates a new ReportAssignmentLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReportAssignmentLogParamsWithHTTPClient(client *http.Client) *ReportAssignmentLogParams {
	var ()
	return &ReportAssignmentLogParams{
		HTTPClient: client,
	}
}

/*ReportAssignmentLogParams contains all the parameters to send to the API endpoint
for the report assignment log operation typically these are written to a http.Request
*/
type ReportAssignmentLogParams struct {

	/*ID
	  The assignment's id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the report assignment log params
func (o *ReportAssignmentLogParams) WithTimeout(timeout time.Duration) *ReportAssignmentLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the report assignment log params
func (o *ReportAssignmentLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the report assignment log params
func (o *ReportAssignmentLogParams) WithContext(ctx context.Context) *ReportAssignmentLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the report assignment log params
func (o *ReportAssignmentLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the report assignment log params
func (o *ReportAssignmentLogParams) WithHTTPClient(client *http.Client) *ReportAssignmentLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the report assignment log params
func (o *ReportAssignmentLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the report assignment log params
func (o *ReportAssignmentLogParams) WithID(id string) *ReportAssignmentLogParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the report assignment log params
func (o *ReportAssignmentLogParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReportAssignmentLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
