// Code generated by go-swagger; DO NOT EDIT.

package assignment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"rpa-sdk/models"
)

// UpdateAssignmentReader is a Reader for the UpdateAssignment structure.
type UpdateAssignmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAssignmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAssignmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateAssignmentOK creates a UpdateAssignmentOK with default headers values
func NewUpdateAssignmentOK() *UpdateAssignmentOK {
	return &UpdateAssignmentOK{}
}

/*UpdateAssignmentOK handles this case with default header values.

Assignment meta info
*/
type UpdateAssignmentOK struct {
	Payload *models.Meta
}

func (o *UpdateAssignmentOK) Error() string {
	return fmt.Sprintf("[PATCH /assignments/{Id}][%d] updateAssignmentOK  %+v", 200, o.Payload)
}

func (o *UpdateAssignmentOK) GetPayload() *models.Meta {
	return o.Payload
}

func (o *UpdateAssignmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Meta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
