// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"models"
)

// AgentReader is a Reader for the Agent structure.
type AgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAgentOK creates a AgentOK with default headers values
func NewAgentOK() *AgentOK {
	return &AgentOK{}
}

/*AgentOK handles this case with default header values.

A heartbeat response is send back to client
*/
type AgentOK struct {
	Payload []*models.Meta
}

func (o *AgentOK) Error() string {
	return fmt.Sprintf("[GET /agents/versions][%d] agentOK  %+v", 200, o.Payload)
}

func (o *AgentOK) GetPayload() []*models.Meta {
	return o.Payload
}

func (o *AgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
